% Import image as img, generated by ProcessReflectanceImages.m
img_lab = rgb2lab(img);
img_l = img_lab(:,:,1);

% Manually select row/column of interest
row = 1026;
col = 950;
img_row = img_l(row,:);
img_col = img_l(:,col).';

% For each element (i.e. pixel) come up with its angle in radians
halfpoint = max(size(img_row))/2;
angleset = zeros(1,max(size(img_row)));

% Uses pixel_width_mm and screen_distance_mm generated by ProcessReflectanceImages.m
for i = 1:max(size(img_row))
    angleset(i) = atan(((i - halfpoint)*pixel_width_mm)/screen_distance_mm);
end

polarplot(angleset,img_col)
hold on
polarplot(angleset,img_row)